### ISSUE TITLE
Issue with ExponentDecimalReal 

### ISSUE THREAD

**Issue by walter-weinmann** [opencypher/openCypher#104]
Should't it be 

`ExponentDecimalReal = ['-'], { Digit | '.' }-, ((e) | (E)), ['-'], DigitString ;`

instead of

`ExponentDecimalReal = ['-'], { Digit | '.' }-, ((E) | (E)), ['-'], DigitString ;`  ?

**Comment by Mats-SX** [comment]
@walter-weinmann No, your suggestion is not correct, but the current behaviour doesn't make much sense either, I'd argue. `E` here is referring to another rule:

```
E = 'E' | 'e' ;
```

The correct way to use this would be the following:

```
ExponentDecimalReal = ['-'], { Digit | '.' }-, E, ['-'], DigitString ;
```

I'm noting several other occasions where we're not casing literal letters correctly. Thank you for reporting this!
