### ISSUE TITLE
Grammar problem: brackets

### ISSUE THREAD

**Issue by walter-weinmann** [opencypher/openCypher#108]
The following queries from the Neo4j Developer Manual v3.0 seem not to be covered by the grammar because of the use of brackets:

**8.3 Where**

```
MATCH (n)
WHERE n.name = 'Peter' XOR (n.age < 30 AND n.name = "Tobias") OR NOT (n.name = "Tobias" OR
  n.name="Peter")
RETURN n
```

**The following is replaced by #113:** 

**9.2.5 Using unique constraints with MERGE**

```
CREATE CONSTRAINT ON (n:Person) ASSERT n.name IS UNIQUE;
CREATE CONSTRAINT ON (n:Person) ASSERT n.role IS UNIQUE;
```

**Comment by Mats-SX** [comment]
@walter-weinmann Could you elaborate on which grammar rule is causing the problem precisely? I can't spot it from the query alone, and the Antlr grammar seems to accept it.

The constraint queries are part of the 'legacy' grammar, and not as highly prioritised.

**Comment by walter-weinmann** [comment]
The problem in 8.3 can be simplified to 

```
MATCH (n)
WHERE (n.name = 'Peter')
```
which gives a syntax error and 

```
MATCH (n)
WHERE n.name = 'Peter'
```
which works and gives me the following parse tree:

```
ParseTree: {cypher,{},
            {statement,
             {query,
              {regularQuery,
               {singleQuery,
                [{clause,
                  {match,[],
                   {pattern,
                    [{patternPart,
                      {anonymousPatternPart,
                       {patternElement,
                        {nodePattern,{variable,{symbolicName,"n"}},{},{}},
                        []}}}]},
                   [],
                   {where,
                    {expression,
                     {expression12,
                      {expression11,
                       {expression10,
                        {expression9,
                         {expression8,
                          {expression7,
                           {expression6,
                            {expression5,
                             {expression4,
                              {expression3,
                               {expression2,
                                {atom,{variable,{symbolicName,"n"}}},
                                [{propertyLookup,
                                  {propertyKeyName,{symbolicName,"name"}},
                                  []}]},
                               []},
                              []},
                             []},
                            []},
                           []},
                          [{partialComparisonExpression,
                            {expression7,
                             {expression6,
                              {expression5,
                               {expression4,
                                {exp.ression3,
                                 {exp.)ression2,
                                  {atom,{stringLiteral,"'Peter'"}},
                                  []},
                                 []},
                                []},
                               []},
                              []},
                             []},
                            "="}]},
                         []},
                        []},
                       []},
                      []}}}}}]},
               []}}},
            []}
```

Perhaps there should be a rule like

`Expression_ = '(' Expression ')' ;
`

(i'll have also a look into 9.2.5)

**Comment by Mats-SX** [comment]
There is a rule with parentheses like that:

```
parenthesizedExpression = '(', Expression, ')' ;
```

I'm not sure why it doesn't work for you. The Antlr4 parser accepts the above query part `MATCH (n)
WHERE (n.name = 'Peter')` as valid. The parse tree it produces is (sorry for the small font):

<img width="284" alt="screen shot 2016-07-08 at 08 46 33" src="https://cloud.githubusercontent.com/assets/2419675/16679539/a68b2f20-44e8-11e6-9ed1-6a2f1b7cdded.png">

Could it be that there is an ambiguous rule somewhere (or several) that trips up your parser implementation? Until now, we haven't had a way to proof-test the ISO EBNF grammar, but we've been using the Antlr4 grammar to validate that the grammar source is correct. Your input here is very valuable.

**Comment by cleishm** [comment]
I would suggest moving to using a precedence climbing algorithm, in both this grammar and in the PEG grammar used by Neo4j.

There's one for the same tree already implemented in [libcypher-parser](https://github.com/cleishm/libcypher-parser/blob/master/src/lib/parser.leg#L402) that might be helpful.
