### ISSUE TITLE
Grammar problem: several consecutive statements

### ISSUE THREAD

**Issue by walter-weinmann** [opencypher/openCypher#113]
The following queries from the Neo4j Developer Manual v3.0 seem not to be covered by the grammar:

**9.2.5 Using unique constraints with MERGE**

```
CREATE CONSTRAINT ON (n:Person) ASSERT n.name IS UNIQUE;
CREATE CONSTRAINT ON (n:Person) ASSERT n.role IS UNIQUE;
```

The grammar does not allow several consecutive statements.

**Comment by Mats-SX** [comment]
I'm pretty sure this is a whitespace problem. I'll provide a fix shortly.

**Comment by walter-weinmann** [comment]
So you mean the EBNF is wrong, since we have:

```
Cypher = WS, Statement, [WS, ';'], WS ;

Statement = Command
          | Query
          ;

Command = CreateIndex
        | DropIndex
        | CreateUniqueConstraint
        | DropUniqueConstraint
        | CreateNodePropertyExistenceConstraint
        | DropNodePropertyExistenceConstraint
        | CreateRelationshipPropertyExistenceConstraint
        | DropRelationshipPropertyExistenceConstraint
        ;
```
which would not allow consecutive commands.

**Comment by Mats-SX** [comment]
Oh, I seem to have misunderstood your concern. No, multiple statements is not supported. If the manual says otherwise, it is wrong.

What I found out was that the above statements didn't parse, because there are whitespace issues in the grammar. There was a rule
```
UniqueConstraint = (C,O,N,S,T,R,A,I,N,T), SP, (O,N), WS, '(', Variable, NodeLabel, ')', (A,S,S,E,R,T), PropertyExpression, (I,S), SP, (U,N,I,Q,U,E) ;
```
which I've now changed to
```
UniqueConstraint = (C,O,N,S,T,R,A,I,N,T), SP, (O,N), WS, '(', Variable, NodeLabel, ')', WS, (A,S,S,E,R,T), SP, PropertyExpression, SP, (I,S), SP, (U,N,I,Q,U,E) ;
```

**Comment by Mats-SX** [comment]
Closing this issue as dealt with.
