### ISSUE TITLE
EBNF grammar problem with SP in CaseAlternatives & CaseExpression

### ISSUE THREAD

**Issue by walter-weinmann** [opencypher/openCypher#128]
A terminal followed by a terminal or an expression and an expression followed by a terminal should be separated by a `SP`?

Hence

```
CaseExpression = (((C,A,S,E), { SP, CaseAlternatives }-) | ((C,A,S,E), SP, Expression, { SP, CaseAlternatives }-)), [SP, (E,L,S,E), SP, Expression], SP, (E,N,D) ;
CaseAlternatives = (W,H,E,N), SP, Expression, SP, (T,H,E,N), SP, Expression ;
```
instead of

```
CaseExpression = (((C,A,S,E), { WS, CaseAlternatives }-) | ((C,A,S,E), Expression, { WS, CaseAlternatives }-)), [WS, (E,L,S,E), WS, Expression], WS, (E,N,D) ;
CaseAlternatives = (W,H,E,N), WS, Expression, WS, (T,H,E,N), WS, Expression ;
```

**Comment by walter-weinmann** [comment]
Same problem with

`FunctionInvocation = FunctionName, WS, '(', WS, [D,I,S,T,I,N,C,T], [SP, Expression, { ',', WS, Expression }], WS, ')' ;`

instead of

`FunctionInvocation = FunctionName, WS, '(', WS, [D,I,S,T,I,N,C,T], [Expression, { ',', WS, Expression }], WS, ')' ;`

?

**Comment by walter-weinmann** [comment]
Same problem with

`FilterExpression = IdInColl, [SP, Where] ;`

instead of

`FilterExpression = IdInColl, [WS, Where] ;`

?

**Comment by Mats-SX** [comment]
@walter-weinmann This is a valid `CASE` expression:

```
CASE(n.prop)WHEN('blue')THEN(1)ELSE(3)END
```

Therefore enforcing space between these parts is not correct.

_Allowing_ whitespace is correct, however, so `WS` rules need to be inserted in some of the places pointed out by you above.
