### ISSUE TITLE
EBNF: RangeLiteral

### ISSUE THREAD

**Issue by walter-weinmann** [opencypher/openCypher#134]
The current definition is

`RangeLiteral = WS, [IntegerLiteral, WS], ['..', WS, [IntegerLiteral, WS]] ;`

Is `WS` really a valid RangeLiteral ?

**Comment by Mats-SX** [comment]
The only usage of `RangeLiteral` is from `RelationshipDetail`:

```
RelationshipDetail = '[', [Variable], ['?'], [RelationshipTypes], ['*', [RangeLiteral]], [Properties], ']' ;
```

It is valid Cypher to give only an asterisk and use the default bounds for variable length patterns, like so:

```
MATCH ()-[r:ACTED_IN*  ]-()
RETURN r
```

So yes, `WS` is a valid `RangeLiteral`. Now, that isn't very helpful, so I think I'll push the asterisk to be parsed as part of the `RangeLiteral` instead, removing the empty string as a valid alternative.
