### ISSUE TITLE
Regular expressions should be marked as legacy

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#136]
The [Standardisation scope of Cypher](https://github.com/opencypher/openCypher/blob/master/docs/standardisation-scope.adoc) states that regular expressions (i.e. the `=~` operator) are to be excluded from openCypher. However, the current grammar allows them: https://github.com/opencypher/openCypher/blob/master/grammar/basic-grammar.xml#L228

I took a quick look at the grammar projects: it seems that only the Production / ProductionResolver classes are able to handle the `legacy` attribute, so marking a single operator legacy is not a trivial task.

**Comment by Mats-SX** [comment]
Yes, you are quite right. That is also the reason I omitted them, for now. It's probably possible to extract the operator into its own production, but it's deferred for now.

**Comment by szarnyasg** [comment]
This was fixed in 3f32723887ef2aef8d98c7f9fb5ddb79c4aeb18a.
