### ISSUE TITLE
NOT operator requires spaces on both sides

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#139]
The `NOT` operator requires a whitespace both before and after the operator: https://github.com/opencypher/openCypher/blob/master/grammar/basic-grammar.xml#L191

``` xml
  <production name="Expression9" rr:inline="true">
    <repeat>&SP; NOT &SP;</repeat>
    <non-terminal ref="Expression8"/>
  </production>
```

Let's investigate this with an example query (inspired by the [Neo4j Cypher documentation](https://neo4j.com/docs/developer-manual/current/cypher/#_selectorantisemiapply).).

This query should be parsed (it works with Neo4j), but it isn't:

```
MATCH (other:Person)
WHERE NOT other.age > 25
RETURN other.name
```

```
line 2:10 mismatched input 'other' expecting {<EOF>, WHITESPACE}
```

This query should be parsed (it works with Neo4j), but it isn't:

```
MATCH (other:Person)
WHERE (NOT other.age > 25)
RETURN other.name
```

```
line 2:11 no viable alternative at input '(NOT other'
line 2:11 mismatched input 'other' expecting {<EOF>, WHITESPACE}
```

In contrast, this query can be parsed as it has a space character before the `NOT` operator.

```
MATCH (other:Person)
WHERE ( NOT other.age > 25)
RETURN other.name
```

As an alternative, this query can be parsed -- it also has a space before the `NOT` operator, but more importantly, the `NOT ...` string is parsed with the `functionInvocation` rule (instead of the `expression9` rule)

```
MATCH (other:Person)
WHERE NOT (other.age > 25)
RETURN other.name
```

**Comment by Mats-SX** [comment]
@szarnyasg Thanks for raising this issue. You're absolutely correct in your methodology; any query that parses in Neo4j should also parse in the openCypher grammars. It's great that you're supplying query examples like this, as it makes fixing these issues a lot easier.
