### ISSUE TITLE
Parsetree always has ws non-terminal symbol even in no space is in the query

### ISSUE THREAD

**Issue by jmarton** [opencypher/openCypher#140]
As ws non-terminal rule allows empty sequence of whitespace, ws always appear in the Cypher query's parse tree even if no space was given. This makes parse tree unnecessarily bushy. They should not appear unless whitespace is given in the input.

**Comment by Mats-SX** [comment]
@thobe What do you think about this?

**Comment by jmarton** [comment]
Other approach could be to use ANTLR's skip on a whitespace lexer rule, but as the primary grammar description is not ANTLR, skip in generated ANTLR could cause differences compared to other parsers.

2016.09.08. dátummal, 9:30 időpontban Mats Rydberg <notifications@github.com> írta:

**Comment by Mats-SX** [comment]
@jmarton Yes, that's why I've shrugged away from using `skip` at all (the suggestion has arisen a few times already), even though it seems to be the standard Antlr approach for whitespace handling.
