### ISSUE TITLE
launch.sh script may create polluted grammar file

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#141]
A small annoyance: if the user does not strictly follow the steps in the [grammar generation instructions](https://github.com/opencypher/openCypher/blob/master/grammar/README.adoc), s/he may enter something like this:

```bash
cd /tmp
git clone git@github.com:opencypher/openCypher
cd openCypher/
mkdir -p grammar/generated
./tools/grammar/src/main/shell/launch.sh Antlr4 cypher.xml > grammar/generated/Cypher.g4
```

It seemingly runs without any output/errors, but upon closer inspection, the `Cypher.g4` file looks like this:

```bash
$ head grammar/generated/Cypher.g4 
/tmp/openCypher/tools/grammar /tmp/openCypher
/tmp/openCypher
/*
 * Copyright (c) 2015-2016 "Neo Technology,"
 * Network Engine for Objects in Lund AB [http://neotechnology.com]
 * 
```

The reason for this is that the output of the `pushd` and `popd` commands is sent to the standard output (and redirected to the `Cypher.g4` file). Fortunately, this can be fixed trivially.

**Comment by Mats-SX** [comment]
Well spotted! I haven't noticed that.
