### ISSUE TITLE
desc keyword not allowed

### ISSUE THREAD

**Issue by crichey** [opencypher/openCypher#164]
This query:
`match (s:Store) where s.storeFormat ='Open' return distinct s.storeFormat order by s.storeFormat desc limit 5` parses fine in the console and BOLT but fails the parser with the following errors:
line 1:97 extraneous input 'desc' expecting {<EOF>, WHITESPACE}
line 1:102 extraneous input 'limit' expecting {<EOF>, WHITESPACE}
line 1:108 extraneous input '5' expecting {<EOF>, WHITESPACE}

**Comment by Mats-SX** [comment]
Yes, neither `DESC` or `ASC` seems to work as expected. Thanks for reporting!
