### ISSUE TITLE
Semantics of collections

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#165]
Similarly to [most RDBMS systems](http://courses.cs.vt.edu/~cs4604/Fall10/lectures/lecture-07-bags-versus-sets.pdf), openCypher uses multiset semantics and users can enforce set semantics with the `DISTINCT` keyword. However, unlike most RDBMSs, Cypher suports lists as attributes. For example, it can use the [`collect`](https://neo4j.com/docs/developer-manual/current/cypher/#aggregation-collect) method to gather a specific attribute from multiple rows.

The simplest example that I can think of:

```
UNWIND [1,2] AS x
RETURN collect(x)
```

Does the specification require that the result is `[1,2]`, or `[2,1]` is also acceptable? (As far as I can tell, Neo4j always returns `[1,2]`.)

As a more general question, is there currently a specification for this, or are there any plans for standardizing when collections should be treated as a multiset or a list?

**Comment by Mats-SX** [comment]
Hello @szarnyasg 

This is a very good question. Currently, there is no specification written for this part of the language, but we do plan to amend this. How and when is still a bit unclear.

**Comment by Mats-SX** [comment]
This is related to #190. I would think that we can define `collect()` to not be dependent on input order, unless special syntax as discussed in #190 is used.
