### ISSUE TITLE
Negative literal numbers absence into Antlr4 grammar

### ISSUE THREAD

**Issue by fcofdez** [opencypher/openCypher#170]
Looking into the Antlr4 it seems like negative integer/double literals are absent:

```
DecimalInteger : ZeroDigit
               | ( NonZeroDigit ( Digit )* )
               ;
```

I think that this can be considered a bug, right?

**Comment by thobe** [comment]
This is actually by design, to avoid ambiguity between unary minus of a positive number and a negative numeral.

Arguably a negative numeral can still be expressed as a unary minus of a positive numeral.

Cheers,
Tobias

**Comment by Mats-SX** [comment]
Tobias is correct, this is by design. Negative numbers are not literals, but evaluated from expressions.
