### ISSUE TITLE
OR/AND in listeners

### ISSUE THREAD

**Issue by pbudzik** [opencypher/openCypher#184]
Hi,

I used OpenCypher ANTLR4 grammar, compiled to Java and in my listener for this query:

MATCH (n) WHERE (n.id='1' OR n.x=3) RETURN n.x

symbolicName enter event is never reported. I can see OR in the whole expression and it's atoms/vars, but never can I see OR alone... How can I get this operator event?  Am I missing anything?

thanks,
P.

**Comment by Mats-SX** [comment]
Hello @pbudzik 

When I try this query out in the latest ANTLR grammar, it seems to work fine. I get this operator tree (truncated, showing only the OR (screenshot from IntelliJ ANTLR plugin)):

![screen shot 2017-02-06 at 09 01 43](https://cloud.githubusercontent.com/assets/2419675/22638820/fb07ddc8-ec4a-11e6-8ede-f917f4de2b2c.png)

The `symbolicName` rule should be entered six times in this query; not sure why you aren't finding that. Can you somehow provide more details on the structure of the parser output (like the picture above, or something similar)?

For the `OR`: it's entered/exited as an `expression12` rule. Is that helpful for you?

**Comment by pbudzik** [comment]
I can dump this: 

(cypher (statement (query (regularQuery (singleQuery (clause (match MATCH   (pattern (patternPart (anonymousPatternPart (patternElement (nodePattern ( (variable (symbolicName n)) (nodeLabels (nodeLabel : (labelName (symbolicName foo)))) ))))))   (where WHERE   (expression (expression12 (expression11 (expression10 (expression9 (expression8 (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (parenthesizedExpression ( (expression (expression12 (expression11 (expression10 (expression9 (expression8 (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (variable (symbolicName n))) (propertyLookup . (propertyKeyName (symbolicName a))))))))) (partialComparisonExpression = (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (literal (numberLiteral (integerLiteral 1)))))))))))))))   or   (expression11 (expression10 (expression9 (expression8 (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (parenthesizedExpression ( (expression (expression12 (expression11 (expression10 (expression9 (expression8 (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (variable (symbolicName n))) (propertyLookup . (propertyKeyName (symbolicName id))))))))) (partialComparisonExpression = (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (literal '1')))))))))))))   OR   (expression11 (expression10 (expression9 (expression8 (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (variable (symbolicName n))) (propertyLookup . (propertyKeyName (symbolicName x))))))))) (partialComparisonExpression = (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (literal (numberLiteral (integerLiteral 3))))))))))))))))) ))))))))))))))) ))))))))))))))))))   (clause (r_return RETURN   (returnBody (returnItems (returnItem (expression (expression12 (expression11 (expression10 (expression9 (expression8 (expression7 (expression6 (expression5 (expression4 (expression3 (expression2 (atom (variable (symbolicName n))) (propertyLookup . (propertyKeyName (symbolicName x)))))))))))))))))))))))))

but the thing is this method:

    @Override
    public void enterSymbolicName(CypherParser.SymbolicNameContext ctx) {
         System.out.println("symbolicName: " + ctx.getText());
    }

never shows me "OR". The problem is that while I am passed all atoms of the expression like field, literal of number etc, I can't know of the OR operator which makes it impossible to handle this in my code.

**Comment by Mats-SX** [comment]
Aha, I see what you mean now. So, the `OR` is not a symbolic name, it is just a necessary piece of the `expression12` rule. That rule is named a bit non-explanatory, but what it encodes is exactly an OR-expression. When you exit the `expression12` rule, your parser stack should contain all the pieces to assemble the OR-expression.

**Comment by pbudzik** [comment]
Ok, makes sense now. Per analogy others represent AND, NOT etc.. Would be easier to notice if named self-explanatory :) Thanks!

**Comment by Mats-SX** [comment]
Good point. I'll raise a PR for renaming them.
