### ISSUE TITLE
On the interpretation of range comparision expressions

### ISSUE THREAD

**Issue by jmarton** [opencypher/openCypher#206]
Accordint to the *Handling numerical ranges 1* test in the [ComparisonOperatorAcceptance] TCK feature file, this query is valid:

```
MATCH (n)
WHERE 1 < n.value < 3
RETURN n.value
```

We have simplified this as follows:

```
RETURN 1 < 2 < 3

Result in Neo4j 3.1.0
---------
true
```

However, the openCypher grammar as well as Neo4j allows the following, but evaluates to false

```
RETURN 1 < 2 < 3 < 4

Result in Neo4j 3.1.0
---------
false
```

I see two options:

 1. we should raise error if the user provides more than 3 operands for a comparision expression
 2. if we allow the above expression, it should evaluate to true

My assumption is te 1st option, i.e. at most 3 operands should be allowed for a range comparision expression, and an error should be raised upon 4 or more operands.

What do you think?

[ComparisonOperatorAcceptance]: https://github.com/opencypher/openCypher/blob/master/tck/features/ComparisonOperatorAcceptance.feature

**Comment by Mats-SX** [comment]
I think that a third option could be `null`, and that associativity is well defined for this case.

```
1 < 2 < 3 < 4 <=> (1 < 2 < 3) < 4 => (1 < 2 AND 2 < 3) < 4 => true < 4 => null
```

But otherwise I agree with you. The Neo4j behaviour doesn't seem to make sense.

**Comment by thobe** [comment]
@Mats-SX I disagree, the interpretation of `1 < 2 < 3 < 4` should be `(1 < 2) AND (2 < 3) AND (3 < 4)`, and nothing else.

**Comment by Mats-SX** [comment]
Do you think this should naturally extend to `n` operands, following the same pattern, and with any mix of comparison operators (`<`, `<=`, `=>`, `>`)? That does seem to be the most consistent interpretation.

Note on my previous comment: I don't think that behaviour is useful, it's just an option in case we wish to limit the expression to maximum three operands.

**Comment by thobe** [comment]
@Mats-SX yes, I don't think we should cap that pattern at 4, it should extend to an arbitrary number, and arbitrary combination of operators. I.e. in a "chain" of comparison operators, each comparison is applied pair-wise over the operands.

**Comment by JanekPo** [comment]
We have controversy on that issue. Two options:
- conservative: n-ary numeric comparison operators are restricted to be "mono" i.e. only one type of operator in a single expression  a < b < c or a >= b >= c  or a = b = c ... etc.   This is pretty mathematical notation, because of transitivity of relation on operands. Possible allowance is weak monotonicity on number sequence:  a < b <= c = d. Paweł supports that option. 
- liberal: any mix of any length of operator sequence is an ordinary syntax shortcut (but not operator composition) as Thobe declared. This might be not readable at the end, especially when inequality operator is used. It's OK for me. By the way "!=" is operator in oC but not in neo4j.

**Comment by jmarton** [comment]
While I understand the point of view raised by @JanekPo, I'd vote for the interpretation given by @thobe:

> interpretation of `1 < 2 < 3 < 4` should be `(1 < 2) AND (2 < 3) AND (3 < 4)`, and nothing else.
> [...]
> it should extend to an arbitrary number, and arbitrary combination of operators

What do you think about drawing conclusion? Does it make sense to turn this issue to a CIR, and later a CIP by extending TCK?

**Comment by Mats-SX** [comment]
@jmarton In terms of process, I think turning this into a CIR seems sensible.

@JanekPo Where is `!=` mentioned as an operator? That smells like a mistake to me. Cypher uses `<>` (like SQL) for expressing inequality.

I also think any combination of comparison operators should be allowed, even things like `STARTS WITH`, etc. Each would just be applied pair-wise:

```
'foo' < 'bar' <> 'baz' STARTS WITH 'arg' > 'quo'
<=>
'foo' < 'bar' AND 'bar' <> 'baz' AND 'baz' STARTS WITH 'arg' AND 'arg' > 'quo'
```

If some operator in the chain is not defined over one of its operands, the whole expression would just evaluate to `null`.

**Comment by jmarton** [comment]
@Mats-SX `!=` is in [basic grammar]

[basic grammar]: https://github.com/opencypher/openCypher/blob/5f23e85ca09113e768441ccb5436331a7f5e502e/grammar/basic-grammar.xml#L316-L317

**Comment by Mats-SX** [comment]
@jmarton Not anymore! Thanks for reporting it.

**Comment by thobe** [comment]
This looks like it has been solved, and the issue has been fixed in Neo4j as well. Closing.
