### ISSUE TITLE
Expected results for empty result set

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#214]
If there are no results for a query, what should an openCypher-compatible engine return - should the header of the results be returned or not?

The TCK tests seem a bit inconsistent for me:

1. [This scenario](https://github.com/opencypher/openCypher/blob/c60357a3c6952b77de78f76a37569385d2e9b694/tck/features/ColumnNameAcceptance.feature#L37) returns the headers and 0 rows.

    ```
      Scenario: Keeping used expression 2
        When executing query:
          """
          MATCH p = (n)-->(b)
          RETURN nOdEs( p )
          """
        Then the result should be:
          | nOdEs( p ) |
        And no side effects
     ```

    I looked for more examples with [The Silver Searcher](https://geoff.greer.fm/ag/) and the following command, resulting in 20 similar scenarios.

    ```
    $ ag "Then the result should be:\s*\|.*\|\s*And" -G ".*feature"
    ```

2. Most other scenarios, for example [this one](https://github.com/opencypher/openCypher/blob/c60357a3c6952b77de78f76a37569385d2e9b694/tck/features/MatchAcceptance.feature#L375), require the result to be empty:

    ```
      Scenario: Do not return anything because path length does not match
        Given an empty graph
        And having executed:
          """
          CREATE (a:A {name: 'A'})-[:KNOWS]->(b:B {name: 'B'})
          """
        When executing query:
          """
          MATCH p = (n)-->(x)
          WHERE length(p) = 10
          RETURN x
          """
        Then the result should be empty
        And no side effects
    ```

    There are 71 in total to be found with:
    
    ```
    $ ag "Then the result should be empty" -G ".*features"
    ```

I tried both scenarios in the Neo4j 3.1.1 web UI and they both return `(no changes, no records)`. But obviously, this output is produced by the UI.

My question is the following: is there a difference between 1. zero rows with a header and 2. empty results?

**Comment by Mats-SX** [comment]
It's an interesting question. We came upon it quite late in the work on writing the TCK, and the decision was to make `Then the result should be empty` supposed to cover the case for when the query ends with an updating clause, rather than a `RETURN` clause. When there's a `RETURN` clause but no records are produced, assertions should still be made on the header making sure that the field names were present and correct.

This of course means that there are a bunch of scenarios that need fixing.
