### ISSUE TITLE
Why are filter and extract considered legacy

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#228]
According to the [standardisation scope document](https://github.com/opencypher/openCypher/blob/72603db1277038c681797abc8d163397166f7ba7/docs/standardisation-scope.adoc#functions-1), both [`filter`](http://neo4j.com/docs/developer-manual/current/cypher/functions/list/#functions-filter) and [`extract`](http://neo4j.com/docs/developer-manual/current/cypher/functions/list/#functions-extract) functions are excluded from openCypher. Besides keeping the openCypher language smaller, I wonder what is the reason behind this.

I believe both functions are just syntax sugar and can be expressed with `UNWIND` and the `collect` aggregation function. This means that any capable openCypher implementation should be able to implement these functions quite easily.

I used the example from the [documentation's source code](https://github.com/neo4j/neo4j-documentation/blob/662a895a893fcd40383517e73baeb69c043ea019/cypher/cypher-docs/src/test/scala/org/neo4j/cypher/docgen/ListFunctionsTest.scala#L29):

```
CREATE
  (alice:Person:Developer {name:'Alice', age: 38, eyes: 'brown'}),
  (bob {name: 'Bob', age: 25, eyes: 'blue'}),
  (charlie {name: 'Charlie', age: 53, eyes: 'green'}),
  (daniel {name: 'Daniel', age: 54, eyes: 'brown'}),
  (eskil {name: 'Eskil', age: 41, eyes: 'blue', array: ['one', 'two', 'three']}),
  (alice)-[:KNOWS]->(bob),
  (alice)-[:KNOWS]->(charlie),
  (bob)-[:KNOWS]->(daniel),
  (charlie)-[:KNOWS]->(daniel),
  (bob)-[:MARRIED]->(eskil)
```

### `filter`

The `filter` function can be expressed using `UNWIND`, `WITH`, `WHERE` and `collect`.

Original query:
```
MATCH (a)
WHERE a.name = 'Eskil'
RETURN a.array, filter(x IN a.array WHERE size(x) = 3) AS threeLetterNumbers
```

Without `filter`:
```
MATCH (a)
WHERE a.name = 'Eskil'
UNWIND a.array AS x
WITH a, x
WHERE size(x) = 3
RETURN a.array, collect(x) AS threeLetterNumbers
```

### `extract`

The `extract` function can be expressed using `UNWIND` and `collect`.

Original query:
```
MATCH p = (a)-->(b)-->(c)
WHERE a.name = 'Alice' AND b.name = 'Bob' AND c.name = 'Daniel'
RETURN extract(n IN nodes(p) | n.age) AS extracted
```

Without `extract`:
```
MATCH p = (a)-->(b)-->(c)
WHERE a.name = 'Alice' AND b.name = 'Bob' AND c.name = 'Daniel'
UNWIND nodes(p) AS n
RETURN collect(n.age) AS extracted
```

*Edit:* I believe the [`all`](https://neo4j.com/docs/developer-manual/current/cypher/functions/predicates/#functions-all) and [`any`](https://neo4j.com/docs/developer-manual/current/cypher/functions/predicates/#functions-any) functions can also be expressed using `WITH`, `UNWIND`, `WHERE` and `collect`.

**Comment by Mats-SX** [comment]
Both of these expressions were replaced by _list comprehensions_, which is both shorter and fits better with the language overall. Both `filter()` and `extract()` look a lot like functions, but they do not take arguments the same way normal functions do.

Extract as list comprehension
```
extract(var IN list | expr) --> [var IN list | expr]
```

Filter as list comprehension:
```
filter(var IN list WHERE predicate) --> [var IN list WHERE predicate | var]
```

**Comment by szarnyasg** [comment]
Thanks for the quick reply. So, for the record, queries using `filter`, `extract`, `any` or `all` can be rephrased in standard openCypher as:

### `filter`

Original:
```
MATCH (a)
WHERE a.name = 'Eskil'
RETURN a.array, filter(x IN a.array WHERE size(x) = 3) AS threeLetterNumbers
```

List comprehension:
```
MATCH (a)
WHERE a.name = 'Eskil'
RETURN a.array, [x IN a.array WHERE size(x) = 3] AS threeLetterNumbers
```

### `extract`

Original:
```
MATCH p = (a)-->(b)-->(c)
WHERE a.name = 'Alice' AND b.name = 'Bob' AND c.name = 'Daniel'
RETURN extract(n IN nodes(p) | n.age) AS extracted
```

List comprehension:
```
MATCH p = (a)-->(b)-->(c)
WHERE a.name = 'Alice' AND b.name = 'Bob' AND c.name = 'Daniel'
RETURN [n IN nodes(p) | n.age] AS extracted
```

### `any`

Original:
```
MATCH (a)
WHERE a.name = 'Eskil' AND ANY (x IN a.array WHERE x = 'one')
RETURN a
```

List comprehension:
```
MATCH (a)
WHERE a.name = 'Eskil' AND size([x IN a.array WHERE x = 'one']) > 0
RETURN a
```

### `all`

Original:
```
MATCH p =(a)-[*1..3]->(b)
WHERE a.name = 'Alice' AND b.name = 'Daniel' AND ALL (x IN nodes(p) WHERE x.age > 30)
RETURN p
```

List comprehension:
```
MATCH p =(a)-[*1..3]->(b)
WHERE a.name = 'Alice' AND b.name = 'Daniel' AND size([x IN nodes(p) WHERE x.age > 30]) = size(nodes(p))
RETURN p
```

**Comment by romanskas** [comment]
Hi Mats, EXTRACT and FILTER are still the current EBNF snapshot: https://s3.amazonaws.com/artifacts.opencypher.org/cypher.ebnf is it intentional or just forgotten?

**Comment by Mats-SX** [comment]
@romanskas You're right. That isn't correct, and should be fixed.
