### ISSUE TITLE
StringLiterals behaving poorly in ANTLR4 grammar

### ISSUE THREAD

**Issue by matt-kempster** [opencypher/openCypher#229]
Hello,

I have struck a bit of a weird bug with the provided Cypher.g4 ANTLR4 grammar when compiling to Python 3 using antlr4-python3-runtime. Before I begin, please note that I have slightly modified the grammar, replacing any instance of the double-quote character '"' with the character '@'. I have done this because I was initially afraid that escape characters were at fault, and because the @ symbol was not used anywhere else in the grammar. This does not change anything bug-wise, and in my opinion improves readability of this particular issue (since there are so many quotes running around). If you have any questions on that part of this issue, let me know.

The grammar (and the subsequent parser and lexer) does well on any input that does not contain StringLiterals. However, when I try to parse a query like this:

`CREATE (n:Person {name: @Andres@, title: @Developer@ })`

it does not work, giving errors that look like this on ANTLR4 v4.7:

```
line 1:26 token recognition error at: '@An'
line 1:33 token recognition error at: '@, '
line 1:36 extraneous input 'title' expecting {',', '}', SP}
line 1:42 mismatched input ':' expecting {',', '}'}
line 1:44 token recognition error at: '@De'
line 1:54 token recognition error at: '@ '
line 1:47 mismatched input 'veloper' expecting ')'
```

Whoa. It appears that ANTLR4 v4.7 decided to interpret implicit tokens three characters at a time. (This, to me, reeks of unicode...) I figured that maybe the problem would be remedied if I added the following rule to the grammar:

`QUOTE : '@' ;`

But the errors got even worse!

```
line 1:26 extraneous input '@' expecting {'(', '[', '+', '-', '{', '$', <INVALID>, <INVALID>, <INVALID>, <INVALID>, <INVALID>, ExponentDecimalReal, RegularDecimalReal, UNION, ALL, OPTIONAL, MATCH, UNWIND, AS, MERGE, ON, CREATE, SET, DETACH, DELETE, REMOVE, WITH, DISTINCT, RETURN, ORDER, BY, L_SKIP, LIMIT, ASCENDING, ASC, DESCENDING, DESC, WHERE, OR, XOR, AND, NOT, IN, STARTS, ENDS, CONTAINS, IS, NULL, COUNT, FILTER, EXTRACT, ANY, NONE, SINGLE, TRUE, FALSE, UnescapedSymbolicName, EscapedSymbolicName}
line 1:33 extraneous input '@' expecting {',', '}', SP}
line 1:44 extraneous input '@' expecting {'(', '[', '+', '-', '{', '$', <INVALID>, <INVALID>, <INVALID>, <INVALID>, <INVALID>, ExponentDecimalReal, RegularDecimalReal, UNION, ALL, OPTIONAL, MATCH, UNWIND, AS, MERGE, ON, CREATE, SET, DETACH, DELETE, REMOVE, WITH, DISTINCT, RETURN, ORDER, BY, L_SKIP, LIMIT, ASCENDING, ASC, DESCENDING, DESC, WHERE, OR, XOR, AND, NOT, IN, STARTS, ENDS, CONTAINS, IS, NULL, COUNT, FILTER, EXTRACT, ANY, NONE, SINGLE, TRUE, FALSE, UnescapedSymbolicName, EscapedSymbolicName}
line 1:54 extraneous input '@' expecting {',', '}', SP}
```

This reminded me of another, closed OpenCypher issue someone submitted (#56), so I thought it might have to do with whitespace. I tried adding and removing whitespace from the query, to no avail. Upon a few other searches having to do with "extraneous input", perhaps it could be due to the lexer not excluding double-quote (or, I guess, at-sign) characters from being interpreted as elements of a variable identifier, though I kinda just made this up.

Worth noting is that before, I had been using ANTLR4 v4.5.3 (I upgraded to see if that would fix the bug), and the bugs were similar; but instead of '@An' being the unrecognized token, it would be just '@A'. Could this bug, perhaps, lie within how ANTLR4 parses unicode characters? (That was one of the major differences I found in the ANTLR4 changelog.) It's possible that this is even the fault of the ANTLR4 Python 3 team, since it seems to be one of the lesser-used branches of ANTLR4.

I would love a speedy response, for I am working on an assignment at the moment. I understand if no such response can be made, however. This bug seems heinous. Recommendations on the order of "well, we've tested it with Python 2/Java/<other language> and it works, so just do that..." will be welcome as well, though it would be magnificent if the Python 3 functionality were vetted.

If you have any questions on how to reproduce the bug, let me know.

Thanks!

**Comment by Mats-SX** [comment]
For a speedy response, I can tell you that our testing only considers the Java parser currently.

**Comment by matt-kempster** [comment]
Do you have any recommendations for as to where I should post this? I am beginning to believe it's more likely an ANTLR4 bug, but anything is possible I suppose...

**Comment by Mats-SX** [comment]
@matt-kempster My first suggestions would be StackOverflow or the Antlr GitHub repository: https://github.com/antlr/antlr4

Which version of the Cypher Antlr grammar are you using? The latest milestone?

**Comment by matt-kempster** [comment]
Yes, I was using the most recent stable snapshot.

**Comment by Mats-SX** [comment]
@matt-kempster Have you been able to resolve your issues? Do you have any conclusions to share?

**Comment by Mats-SX** [comment]
@matt-kempster Closing this for now, as it is unclear that we can do anything to fix this issue. Please reach back and we can re-open if something else comes up.
