### ISSUE TITLE
Different results from Neo4j and TCK 

### ISSUE THREAD

**Issue by zsambek** [opencypher/openCypher#235]
The results are different in Neo4j's WebUI and in the following tests in the TCK.

In test [Comparing strings and integers using > in an AND'd predicate ](https://github.com/opencypher/openCypher/blob/1d8d25f0db858fbae6a6c598a338d5b709f7229d/tck/features/Comparability.feature#L19) the result should be:
```
    | i.id |
    | 'xx' |
```
But Neo4j's WebUI (3.1.3) provides the following result: 
```
Don't know how to compare that. Left: 0 (Long); Right: "x" (String)
Neo.ClientError.Statement.TypeError
```
And in test [Comparing strings and integers using > in a OR'd predicate](https://github.com/opencypher/openCypher/blob/1d8d25f0db858fbae6a6c598a338d5b709f7229d/tck/features/Comparability.feature#L38) the result should be: 
```
    | i.id |
    | 'xx' |
    | null |
```
But Neo4j's WebUI (3.1.3) provides the following result: 
```
Don't know how to compare that. Left: 0 (Long); Right: "x" (String)
Neo.ClientError.Statement.TypeError
```

Which would be the right result?

**Comment by Mats-SX** [comment]
Hello @zsambek 

The correct result is the one listed in the TCK, which is in conformance with the [comparability CIP](https://github.com/opencypher/openCypher/blob/master/cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc). Neo4j does not fully implement this yet.

**Comment by zsambek** [comment]
Hi @Mats-SX 

I tought all TCK tests should pass on Neo4j, but it's clear now.
Thanks for your reply!

**Comment by Mats-SX** [comment]
@zsambek I wish that were true :)
