### ISSUE TITLE
Ideas for introducing LOAD CSV

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#249]
I am currently working on an [APOC procedure](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/489) that takes CSV files with headers confirming the Neo4j import tools' [header format](http://neo4j.com/docs/operations-manual/3.2/tools/import/file-header-format/) and generate `LOAD CSV` queries accordingly.

### Current usages

I'll illustrate the generation with an example.

For loading the following `Person` nodes:

```
:ID|name:STRING
1|John
2|Jane
```

it generates

```
LOAD CSV FROM 'file:/id.csv' AS line FIELDTERMINATOR '|'
WITH line
SKIP 1
WITH
  toInteger(line[0]) AS `__csv_id`,
  line[1] AS `name`
CREATE (n:`Person` {`__csv_id`: `__csv_id`, `name`: `name`})
RETURN count(n) AS count
```

For loading the following `KNOWS` relationships

```
:START_ID|:END_ID|since:INT
1|2|2016
```

it generates

```
LOAD CSV FROM 'file:/rel-on-ids.csv' AS line FIELDTERMINATOR '|'
WITH line
SKIP 1
WITH
  toInteger(line[0]) AS `__csv_start_id`,
  toInteger(line[1]) AS `__csv_end_id`,
  toInteger(line[2]) AS `since`
MATCH
  (src {`__csv_id`: `__csv_start_id`}),
  (trg {`__csv_id`: `__csv_end_id`})
CREATE (src)-[r:`KNOWS` {`since`: `since`}]->(trg)
RETURN count(r) AS count
```

What's interesting in these queries is that other than `LOAD CSV`, they only  only use standard Cypher constructs.

I also created a [Gist with more details on mapping CSV fields](https://gist.github.com/szarnyasg/f387c60b465f7dee5140dfddcde2d8ce).

### The case against LOAD CSV

This work got me thinking on why `LOAD CSV` is not included in openCypher. I believe the main reason behind this is simplicity:

1. non-legacy openCypher is capable of building any possible graph with `CREATE` (and optionally `MERGE`, `SET`, ...) commands.
2. `LOAD CSV` is quite difficult to implement in a cross-platform way (file system handling, character encoding, newlines, etc.).

### The case for LOAD CSV

Building a graph with `CREATE` operations for each node/relationship is very slow -- even the cost of parsing the query is quite expensive. Meanwhile, `LOAD CSV` could provide a more efficient alternative. Most of the cross-platform issues can be specified (e.g. [URIs](https://www.ietf.org/rfc/rfc3986.txt) are already well-defined).

So while I completely agree with `LOAD CSV` excluded from core openCypher, maybe it would make a useful extension or could be proposed as a [module](https://s3.amazonaws.com/artifacts.opencypher.org/website/ocim1/slides/16-20+-+Language+Evolution-+Conformance+and+Extension.pdf#page=15) (e.g. `load` module).

### Potential extensions

It would be possible to support loading CSV-files with headers confirming the import tool's format. For example:

```
LOAD CSV FROM 'file:/id.csv' TO NODES ['Person'] FIELDTERMINATOR '|'
LOAD CSV FROM 'file:/rel-on-ids.csv' TO RELATIONSHIPS 'KNOWS' FIELDTERMINATOR '|'
```

Note: the `WITH HEADERS` option does not make sense in this case, as it *only works* with headers.

To provide similar features to the [command line client](https://neo4j.com/docs/operations-manual/current/tools/import/command-line-usage/) would require some additional (optional) settings such as `ARRAYDELIMITER`,  `QUOTE` and `IDTYPE`.

**Comment by Mats-SX** [comment]
When cutting the standardisation scope, I believe our take on `LOAD CSV` was that the functionality it provided was a better fit for a procedure. The procedure could run a `CREATE`-based query, or use an engine-specific API (more likely for bulk imports I would say). In my view, bulk loading is performed only a very few number of times per graph/database, and the need for integrated syntax is thus lessened. Also very little query planning is required, unless the bulk import is `MERGE`-based -- but perhaps that is better solved by working with multiple graphs?
