### ISSUE TITLE
Query not accepted by grammar

### ISSUE THREAD

**Issue by JanekPo** [opencypher/openCypher#253]
Hello,
our tests show that query:

```
MATCH ()
CREATE ()
WITH *
CREATE ()
```
is not accepted by the grammar in version M07.
Link to the query in features file.

https://github.com/opencypher/openCypher/blob/931e4a10837de37a4be8412126a0be830fa7925e/tck/features/CreateAcceptance.feature#L239

**Comment by Mats-SX** [comment]
Similar problem as #265
