### ISSUE TITLE
EXCLUDE MATCH operator

### ISSUE THREAD

**Issue by sherfert** [opencypher/openCypher#258]
# CIR-2017-258

This proposes an EXCLUDE MATCH clause, which must follow a WITH, as it has no meaning when not using variables from a previous MATCH. After the EXCLUDE MATCH, the in-scope variables should be the same ones that were piped in with the last WITH.

The purpose is to look for pattern match using previously defined variables, and then remove any rows where that pattern occurs.

This behavior can be replicated currently in Cypher by looking for a pattern with OPTIONAL MATCH, WHERE the resulting pattern is null.

An example of usage - in a graph of :Patients and :Doctors (where :Doctors may work with other :Doctors), I'm looking for :Patients whose :Doctor (or any Doctor they are associated with through chained :WorksWith relationships, however distantly) is not Doctor Frankenstein or Doctor Claw.

In current Cypher I might use this:

```
WITH ['Frankenstein', 'Claw'] as badDoctors
MATCH (patient:Patient)-[:TreatedBy]->(doctor:Doctor)
WHERE doctor.name NOT IN badDoctors
WITH patient, doctor
OPTIONAL MATCH badDoctorPattern = (doctor)-[:WorksWith*]-(badDoctor:Doctor)
WHERE badDoctor.name IN badDoctors
WITH patient, doctor, badDoctorPattern
WHERE badDoctorPattern IS NULL
RETURN patient
```
With the new EXCLUDE MATCH clause, we don't save too many lines, but it should make the intent of the query more clear:

```
WITH ['Frankenstein', 'Claw'] as badDoctors
MATCH (patient:Patient)-[:TreatedBy]->(doctor:Doctor)
WHERE doctor.name NOT IN badDoctors
WITH patient, doctor
EXCLUDE MATCH (doctor)-[:WorksWith*]-(badDoctor:Doctor)
WHERE badDoctor.name IN badDoctors
RETURN patient
```
The above example could of course be optimized to match on the bad :Doctors first, then use WHERE NOT EXISTS() and supply the badDoctor pattern, avoiding the need for any kind of match.

While that circumvents the need for an EXCLUDES MATCH here, there are other cases where a pattern alone is not rich enough to express what's needed (maybe there needs to be a predicate on the relationship, or some other condition where a predicate needs to be present). EXCLUDES MATCH lets us tackle queries where NOT EXISTS(pattern) isn't rich enough for our needs, and where the OPTIONAL MATCH workaround obfuscates the intent of the query.

**Comment by sherfert** [comment]
See https://github.com/opencypher/openCypher/issues/239 for the original discussion. Also, ping @InverseFalcon

**Comment by thobe** [comment]
I would think that [Existential subqueries](https://github.com/openCypher/openCypher/blob/master/cip/1.accepted/CIP2015-05-13-EXISTS.adoc) should solve this, but if someone could share some use cases where these are insufficient, that would be great.
