### ISSUE TITLE
New TCK: Support ignoring column ordering in Result

### ISSUE THREAD

**Issue by pstutz** [opencypher/openCypher#276]
org.opencypher.tools.tck.api.Scenario$ScenarioFailedException: Feature "KeysAcceptance": Scenario "Using `keys()` on a parameter map" failed with message: 
Expected (in any order of rows):
| k |
| ['address', 'name', 'age'] |
Actual:
| k |
| ['name', 'age', 'address'] |

**Comment by thobe** [comment]
This is possible through saying `(ignoring element order for lists)`, and the scenario has been fixed by doing that.
