### ISSUE TITLE
REMOVE property from nodes returned by an expression

### ISSUE THREAD

**Issue by jmarton** [opencypher/openCypher#287]
When using the `REMOVE` clause to remove a property of a node or relationship, grammar defines it as a property lookup on an `Atom` as seen in the extract from the grammar:

https://github.com/opencypher/openCypher/blob/c1a86ad471c475fbc934a2564ee69a41a7889c0e/grammar/cypher.xml#L272-L277

https://github.com/opencypher/openCypher/blob/c1a86ad471c475fbc934a2564ee69a41a7889c0e/grammar/basic-grammar.xml#L496-L499

`Atom` might be substituted with a variable, and many different types of expression. Removing a property from a node or relationship referred to by a variable is OK. My question is basically whether we want to allow removing a property from a node or relationship, where the node or relationship is defined in an expression?

The following example attempt to remove the age from the older one of Alice and Bob, but raises an error in Neo4j 3.2.3:

```
MATCH (a:Person {name: 'Alice'})-[:KNOWS]->(b:Person {name: 'Bob'})
REMOVE CASE WHEN a.age>b.age THEN a ELSE b END.age
RETURN a, b
```

The following error is raised:

> Neo.DatabaseError.Statement.ExecutionFailed
> 
> REMOVE RemovePropertyItem(Property(CaseExpression(None,Vector((GreaterThan(Property(Variable(a),PropertyKeyName(age)),Property(Variable(b),PropertyKeyName(age))),Variable(a))),Some(Variable(b))),PropertyKeyName(age))) not supported in cost planner yet

**Comment by Mats-SX** [comment]
@jmarton I think that should be supported yes. I don't see a good reason to not allow queries such as the one in your example. Neo4j failing is a bug -- you can f.e. run this in Neo4j 2.3 (or with 2.3 compatibility mode in any 3.x version).

**Comment by jmarton** [comment]
Thank you, @Mats-SX. Closing this in favor of the issue filed against Neo4j.
