### ISSUE TITLE
Property lookup and label constraint expression

### ISSUE THREAD

**Issue by jmarton** [opencypher/openCypher#288]
According to the grammar, `PropertyOrLabelsExpression` is built as

> `Atom` ( `PropertyLookup` | `NodeLabels` )*

https://github.com/opencypher/openCypher/blob/c1a86ad471c475fbc934a2564ee69a41a7889c0e/grammar/basic-grammar.xml#L258-L267

A few legal forms of this expression I know of are as follows:

 - filter by labels of the node variable
```
MATCH (p)
WHERE p:Person:Teacher
RETURN p
```

 - extract a node from a map, and optionally filter on its labels
```
MATCH (p)
WHERE {foo: p}.foo:Person:Teacher
RETURN p
```

But I know of no legal uses where `PropertyLookup` might follow `NodeLabels`, i.e. the following is illegal:
```
MATCH (p)
WHERE p:Person:Teacher.name
RETURN p
```

The error returned in Neo4j 3.2.3:

> Neo.ClientError.Statement.SyntaxError
> 
> Type mismatch: expected Any, Map, Node or Relationship but was Boolean (line 2, column 8 (offset: 17))
> "WHERE p:Person:Teacher.name"

This makes me to think of the following grammar form as a better solution, as `NodeLabels` is already a sequence of labels:

`Atom` `PropertyLookup`* `NodeLabels`?

https://github.com/opencypher/openCypher/blob/c1a86ad471c475fbc934a2564ee69a41a7889c0e/grammar/basic-grammar.xml#L149-L152

Is there any working examples or future plans that needs the current grammar for `PropertyOrLabelsExpression`, i.e. where a node label constraint is followed by a property lookup? If not, I would be happy to submit a PR to rewrite this part of the grammar.

**Comment by Mats-SX** [comment]
Since `NodeLabels` is always a boolean expression, I don't see a good reason to allow it in the grammar the way it is now. I think your suggestion seems sensible.
