### ISSUE TITLE
Query parts in the grammar w.r.t. UNWIND

### ISSUE THREAD

**Issue by jmarton** [opencypher/openCypher#322]
Before openCypher 1.0-M09, a SingleQuery (i.e. a query w/o `UNION` or between two `UNION`s) was grammatically described as an ordered list of clauses and the consumer of the parsed AST was responsible for identifying parts of the query (if needed).

openCypher 1.0-M09 and M10 aimed at identifying query parts at the grammar level, thus pushing down some of the semantical constraints on possible clause sequences to the grammar level: a SingleQuery is now further specialized to either a [SinglePartQuery] or a [MultiPartQuery]. A MultiPartQuery, in turn, consists of a sequence of (implicit) MultiPartSubQueries (i.e. the repeating part in the grammar excerpt shown below) followed by a SinglePartQuery.

https://github.com/opencypher/openCypher/blob/15157c0fe4243da1cbfe2c372bcd00fec77a5c17/grammar/cypher.xml#L129-L140

As of my understanding, the `UNWIND` clause is similar to `WITH` and `RETURN` from the point of view that it defines the result set that streams to the next query processing stages.

Before M09, I treated a query part to match the regexp-like clause sequence expression given below, meaning that `UNWIND` concluded a query part, but `WITH` concluded only if it was not followed by UNWIND.
`(MATCH*)((CREATE|DELETE)+ RETURN?|(WITH UNWIND?)|UNWIND|RETURN)`

Let's take a look at the example query:
```
/* 1 */ MATCH (n:Person)
/* 2 */ WITH collect(n) as persons
/* 3 */ UNWIND persons as p2
/* 4 */ UNWIND p2.languages as lang
/* 5 */ MATCH (p2)-->(x:Foo)
/* 6 */ RETURN p2, x, lang
```

 i. openCypher 1.0-M10 tells this consists of 2 query parts: lines 1-2 and lines 3-6.
 ii. in my interpretation of UNWIND as given above, this consists of 3 query parts: lines 1-3, line 4 and lines 5-6.

Explaining the plan for the example query in Neo4j 3.4, the plan displayed below is given. It suggests that line 5 is treated as a start of a new query part by findind matches for the pattern `(p2)-->(x:Foo)`, and not expanding on the result of UNWIND. This seems to be in line with my interpretation described in (ii.) stating that UNWIND concludes a query part.

![neo4j-34-unwind](https://user-images.githubusercontent.com/10688599/44001819-fdf6032e-9e38-11e8-9a90-8991109c8c2c.png)

What do you think of the options (i.) and (ii.)? Should `UNWIND` always conclude a query part (as in ii.), or should it be mixed with reading clauses as in the current grammar?

I would be happy to learn your understanding, and if we end up with option (ii.), I will be happy to prepare a PR.

[SinglePartQuery]: https://s3.amazonaws.com/artifacts.opencypher.org/M10/railroad/SinglePartQuery.html
[MultiPartQuery]: https://s3.amazonaws.com/artifacts.opencypher.org/M10/railroad/MultiPartQuery.html

**Comment by Mats-SX** [comment]
I agree that `UNWIND` is similar to `WITH` in several regards, but there is a key characteristic that is unique to `WITH` in that it allows _aggregations_. This unique ability is what makes it most suitable as a delimiting clause, as it is then able to act as a query _horizon_, across which some fields are no longer accessible. `UNWIND` may only add to the set of available fields, while `WITH` may modify this in many aspects. One could say that each `WITH` is empowered to set the query _context_; which fields are available to the next clause.

Now, what Neo4j implements needn't follow this setup. The way I interpret the execution plans Neo4j may provide differs somewhat from how I interpret the internal structure of a query semantically and syntactically. The Neo4j execution plan offers a solution view, including starting points and directed computational flow; it is often only one of many different solutions to a given query.

I believe `WITH` is well suited to be the only delimiting clause between so-called query parts, insofar as these parts are then separated by a horizon (even though sometimes that horizon isn't actually hiding anything and may be optimised away). That way we may define characteristics of what goes on in a query part:

- declared fields are not overwritten (scoping)
- clauses may only declare variables, not remove them

And perhaps more that I can not come up with right now. What are your thoughts on that?

**Comment by jmarton** [comment]
I like the point of view of `WITH` being a *query horizon* having the unique ability to remove variables from the scope.

I think this is a convincing reasoning and what's more, treating `WITH` as the only query part delimiter undoubtedly keeps the language structure as simple as it can be.

So I would go for option (i.), as it is in the current grammar. Thank you for sharing your thoughts!

**Comment by Mats-SX** [comment]
Very nice, I'll close this as settled for now.
