### ISSUE TITLE
Parse error of "CALL-WHERE-RETURN" clause using ANTLR4 grammar

### ISSUE THREAD

**Issue by wangtao9** [opencypher/openCypher#344]
When I parse the query:
```
CALL db.labels() YIELD label
WHERE label CONTAINS 'User'
RETURN count(label) AS numLabels
```
I get: 
`line 9:0 no viable alternative at input '\nWHERE'`

It seems there is no rule to match the above query?

**Comment by thobe** [comment]
Thank you for reporting this. It does indeed seem like the `CALL`-portion of the grammar is incomplete.

**Comment by Mats-SX** [comment]
Is `WHERE` allowed directly after a `CALL` clause? I thought `WHERE` was only allowed after `MATCH` and after `WITH`.

**Comment by thobe** [comment]
The Neo4j Cypher parser seems to allow `WHERE` without a `WITH` in between: https://github.com/neo4j/neo4j/blob/3.5/community/cypher/front-end/parser/src/main/scala/org/neo4j/cypher/internal/v3_5/parser/ProcedureCalls.scala#L44

**Comment by Mats-SX** [comment]
You're right! The CIP also clearly allows this: https://github.com/opencypher/openCypher/blob/master/cip/1.accepted/CIP2015-06-24-call-procedures.adoc#226-filtering-yielded-records

Then I agree that this is a bug.
