### ISSUE TITLE
Why propertyExpression  has repeatable propertyLookup?

### ISSUE THREAD

**Issue by hagen666** [opencypher/openCypher#379]
Hi,
I read the Cypher.g4 file and have many questions.
One is about the propertyLookup.

Here is the grammar rule:  

> oC_PropertyExpression : oC_Atom ( SP? oC_PropertyLookup )+ ;

Why a PropertyExpression can have multiple PropertyLookup? 
Are there any example queries?

**Comment by thobe** [comment]
Cypher allows nested records/maps/elements.

It is pretty straightforward to imagine a simple example:

```
MATCH (p:Person)-[:LIVES_IN]->(city)<-[:LIVES_IN]-(q:Person), (p)-[:KNOWS]-(q)
WITH city.name AS location, collect({first:p, other:q}) AS friends
WHERE size(friends) < 5
UNWIND friends AS f
RETURN location, f.first.name, q.other.name
```

Which returns the names of friends who live in the same city, in cities where there are less than five such pairs of friends. (a bit of a silly query, maybe, but it shows a pretty straightforward scenario where this is useful)

**Comment by hagen666** [comment]
Thank You!
