### ISSUE TITLE
Why is the terminal-node 'DISTINCT' outside of the oC_ReturnBody? 

### ISSUE THREAD

**Issue by hagen666** [opencypher/openCypher#381]
Hi,
I'm reading the Cypher.g4 file these days and have many questions.
One is about **oC_With** & **oC_Return**.

> oC_With : WITH ( SP? DISTINCT )? SP oC_ReturnBody ( SP? oC_Where )? ;
> oC_Return : RETURN ( SP? DISTINCT )? SP oC_ReturnBody ;
> oC_ReturnBody : oC_ReturnItems ( SP oC_Order )? ( SP oC_Skip )? ( SP oC_Limit )? ;

Wherever the **oC_ReturnBody** appears, it always has the  **( SP? DISTINCT )?**  as the prefix.
Since the **oC_ReturnBody** and **DISTINCT** always appear altogether, why not use rules like this style?

> oC_With : WITH oC_ReturnBody ( SP? oC_Where )? ;
> oC_Return : RETURN oC_ReturnBody ;
> oC_ReturnBody : ( SP? DISTINCT )? SP oC_ReturnItems ( SP oC_Order )? ( SP oC_Skip )? ( SP oC_Limit )? ;

Are there any unpublished rules or considerations?

**Comment by Mats-SX** [comment]
If it's true like you say that the `returnBody` appears always prefixed by the `DISTINCT`, then I think what you say makes sense.

I created a PR #382 which does this, and it seems fine.

Thanks for the contribution!

**Comment by hagen666** [comment]
Wow, it's my honor to make the contribution!
