### ISSUE TITLE
How to generate Railroad diagrams/EBNF/ANTLR grammar

### ISSUE THREAD

**Issue by szarnyasg** [opencypher/openCypher#41]
The README mentions that

> A more readily consumable form of the grammar is generated as output from the build

How can I generate these outputs? I tried various Maven commands (e.g. `mvn compile test`), but none produced the `ebnf`/`g4`/`html` files. I also tried searching the code, but did not find the related code.

**Comment by Mats-SX** [comment]
Hello @szarnyasg and thanks for your question. I'll answer you briefly here and write a more comprehensive guide in the readme in a bit.

`mvn clean install` to generate the required jars, then run these four commands (which can be found in the `.travis.yml` file) for the artifacts that currently may be generated:

```
./tools/grammar/src/main/shell/launch.sh RailRoadDiagramPages -outputDir=grammar/generated/railroad cypher.xml
./tools/grammar/src/main/shell/launch.sh RailRoadDiagrams -DRailRoadDiagrams.inlineNone=true -outputDir=grammar/generated/railroad/raw cypher.xml
./tools/grammar/src/main/shell/launch.sh ISO14977 cypher.xml > grammar/generated/cypher.ebnf
./tools/grammar/src/main/shell/launch.sh Antlr4 cypher.xml > grammar/generated/Cypher.g4
```

These commands are mostly self-explanatory, and will put all artifacts in `grammar/generated`, unless modified.

**Comment by Mats-SX** [comment]
Closing this as answered.
