### ISSUE TITLE
Missing test query

### ISSUE THREAD

**Issue by AviAvni** [opencypher/openCypher#432]
The query in the test is not correct https://github.com/opencypher/openCypher/blob/35f7e54042eadeac33c5986c91cf1e0b1a528a70/tck/features/expressions/comparison/Comparison1.feature#L130

there are a lot of tests with queries like this

**Comment by Mats-SX** [comment]
Hello @AviAvni and thanks for reaching out to us. You're almost correct; this query is not verbatim Cypher syntax. However, the scenarios are written in Gherkin, which supports the `Scenario Outline` feature. In that feature the angle brackets (`<`, `>`) indicate a parameter which is substituted by values from the following `Examples` table. So the actual Cypher queries that belong to this `Scenario Outline` look like this:

```
RETURN [1, 2] = [1] AS result
```

which is valid. You can also find that the result is similarly parameterised.

**Comment by AviAvni** [comment]
ok thanks
