### ISSUE TITLE
Temporal values

### ISSUE THREAD

**Issue by AviAvni** [opencypher/openCypher#438]
Running this query in neo4j 4.1 the result is different
https://github.com/opencypher/openCypher/blob/7fa3b86bace36ac9b76047f6d67b47a81cc14076/tck/features/expressions/temporal/Temporal1.feature#L336
this is the result I get (without the offset)
1984-10-11T12:31:14.645876123[Europe/Stockholm]

**Comment by thobe** [comment]
Which client are you using? I believe the representation without offset could come from the string representation rendered by your client.

If I for example try to replicate this issue in the Neo4j browser, I get the same results as you.

Query:

    RETURN datetime({year: 1984, month: 10, day: 11, hour: 12, minute: 31, second: 14, nanosecond: 645876123, timezone: 'Europe/Stockholm'})

Result:

    "1984-10-11T12:31:14.645876123[Europe/Stockholm]"

However, if I perform the conversion to a string representation of the datetime value on the server side within Cypher, I get the same results as that test case expects:

Query:

    RETURN toString(datetime({year: 1984, month: 10, day: 11, hour: 12, minute: 31, second: 14, nanosecond: 645876123, timezone: 'Europe/Stockholm'}))

Result:

    "1984-10-11T12:31:14.645876123+01:00[Europe/Stockholm]"

Could that be the same difference as you are experiencing?

What problems is the difference causing for you?

**Comment by AviAvni** [comment]
browser

**Comment by thobe** [comment]
This client-side difference in textual representation is not a new phenomenon by the way, a quick test with older versions of Neo4j I happened to have running on my machine confirms that the same difference between server-side textual representation and client-side textual representation goes back to 3.4 as well.

**Comment by AviAvni** [comment]
I'm trying to understand from where the offset is come

**Comment by AviAvni** [comment]
Ok I found how to calculate it

**Comment by thobe** [comment]
The offset is the difference in time from UTC in the `Europe/Stockholm` timezone on that date.

On October 11 1984 time in Sweden was one (1) hour ahead of UTC, as were the other countries that were in the `CET` ("Central European Time") time zone on that date.

The Swedish timezone changes its offset from UTC twice per year. During the winter Sweden is in the `CET` (`UTC+01:00`) timezone. During the summer Sweden is in the `CEST` ("Central European Summer Time", `UTC+02:00`) timezone.

**Comment by AviAvni** [comment]
thanks
