### ISSUE TITLE
duration format

### ISSUE THREAD

**Issue by AviAvni** [opencypher/openCypher#453]
In the browser and cypher shell I get different result
https://github.com/opencypher/openCypher/blob/d8c5d6675c90718f714f8aa3964627ad9bdafb7d/tck/features/expressions/temporal/Temporal1.feature#L393

![image](https://user-images.githubusercontent.com/1097246/95683663-5a9c0700-0bf5-11eb-95ac-5145446d7888.png)

**Comment by thobe** [comment]
The difference is in how the value is formatted as text. Both values express 22 days (although the Cypher shell and Neo4j Browser version also expresses 0 months, which is redundant information). Then the server side formatted version says 19 hours, 51 minutes and 49.5 seconds, while the Neo4j Browser / Cypher shell version says 71509.5 seconds (the trailing zeros make for a different string, but are insignificant). 19 hours, 51 minutes and 49.5 seconds is in fact the same as 71509.5 seconds. The result is the same, but the textual formatting is different.

If you in the Neo4j Browser or Cypher shell were to try `toString(duration({months: 0.75}))` instead, you would get the same result as in the test case.

I would say that this looks like a text formatting issue in Neo4j Browser and Neo4j Cypher shell, and not an issue with the openCypher TCK.
