### ISSUE TITLE
map format

### ISSUE THREAD

**Issue by AviAvni** [opencypher/openCypher#454]
please format this correctly
https://github.com/opencypher/openCypher/blob/d8c5d6675c90718f714f8aa3964627ad9bdafb7d/tck/features/uncategorized/AggregationAcceptance.feature#L341

**Comment by hvub** [comment]
[Done.](https://github.com/opencypher/openCypher/blob/master/tck/features/uncategorized/AggregationAcceptance.feature#L341)

Thanks for point out. 👍

**Comment by thobe** [comment]
Closing. Since this has been fixed.
