### ISSUE TITLE
Deleting the relationship for the dynamic labels in UNWIND

### ISSUE THREAD

**Issue by Devikaelangovan** [opencypher/openCypher#472]
Hi,

I want to delete the relationship for the dynamic labels inside the UNWIND.

Here is my scenario:

I am creating a labels for the relationship dynamically based on the country where order placed.
I am using UNWIND option to perform the operation for bulk data.

**Example:**

(m:Person) -[r: COUNTRY_{COUNTRY_NAME}]->(n:Order)

Since dynamic label creation option is not available for relationship, i used apoc.merge.relationship procedure to create the relationship.

Now for the same relationship type, Using UNWIND, I want to delete the relationship based on the condition.

How can we achieve it?

**Comment by thobe** [comment]
You could do something like:

```
MATCH (m: Person)-[r]->(n: Order)
WHERE type(r) = 'COUNTRY_' + $countryName
DELETE r
```

In general, questions like this are better targeted at a user support forum. I know there are people who monitor StackOverflow for questions about Cypher. There is also the Neo4j online community with lots of people willing to help with Neo4j-related questions, including help with using Cypher with Neo4j: https://community.neo4j.com/

This bug tracker is for development of the Cypher query language.
