### ISSUE TITLE
Performance is very poor for the create/update relationships 

### ISSUE THREAD

**Issue by Devikaelangovan** [opencypher/openCypher#474]
Hi,

Is there any way to improve performance for Create/update relationships?

I want to insert Millions of records. For Nodes we are using indexes, so performance is good.
But for relationship, there is no way to create index. performance is very very poor.

`(m:User)-[r:COUNTRY_INDIA]->(o:Order)`

Can someone help to improve the performance?

**Comment by thobe** [comment]
Performance issues are dependent on the implementation and such questions should be directed at the vendor.
Please contact the support team of the makers of the database you are using.
